## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [8]:
#create a numpy array of 5 zeros.
import numpy as np
a=np.zeros(5)

In [2]:
#check datatype, itemsize and shape of above
a=np.zeros(5)
print(a.dtype)
print(a.itemsize)
print(a.shape)
print(a.ndim)

float64
8
(5,)
1


In [4]:
#create a numpy array of ones of shape (5,4)

x=np.ones((5,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#create a matrix of shape 4,5 with numbers from 1-20
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(x.shape)
print(x)

(4, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
#multiply all elements of above array by 10

y=(x*10)
print(y)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [18]:
#print odd elements from array
i=(x%2!=0)
print(x[i])
print(y[i])

[ 1  3  5  7  9 11 13 15 17 19]
[ 10  30  50  70  90 110 130 150 170 190]


In [17]:
#replace all even elements by their negative
print(~x)
print(~y)

[[ -2  -3  -4  -5  -6]
 [ -7  -8  -9 -10 -11]
 [-12 -13 -14 -15 -16]
 [-17 -18 -19 -20 -21]]
[[ -11  -21  -31  -41  -51]
 [ -61  -71  -81  -91 -101]
 [-111 -121 -131 -141 -151]
 [-161 -171 -181 -191 -201]]


In [21]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
m1=np.arange(1,17).reshape(4,4)
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [51]:
# create a transpose of above matrix call it M2
m2=(m1.T)
print(m2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [52]:
# find sum of above matrix M3 = (M1 + M2)
print(m1)
print()
print(m2)
print()
m3=(sum(m1,m2))
print(m3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[29 37 45 53]
 [30 38 46 54]
 [31 39 47 55]
 [32 40 48 56]]


In [53]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
mt1=(m3.T)
print(mt1)

[[29 30 31 32]
 [37 38 39 40]
 [45 46 47 48]
 [53 54 55 56]]


In [42]:
print(m3)
print()
print(mt1)
print()
print(mt1==m3)

[[29 38 47 56]
 [30 39 48 57]
 [31 40 49 58]
 [32 41 50 59]
 [33 42 51 60]]

[[29 30 31 32 33]
 [38 39 40 41 42]
 [47 48 49 50 51]
 [56 57 58 59 60]]

False


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """


In [54]:
#find diffrence of M4 = (M1 - M2)

print(m1)
print()
print(m2)
m4=m1-m2
print(m4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [55]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

print(m4)
print()
print(m4.T)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]


In [93]:
# create a matrix (3x4) R1 of random numbers between 10-40
r1=np.random.randint(10,40,size=(3,4))
print(r1)

[[16 19 26 30]
 [36 19 27 34]
 [16 39 29 12]]


In [94]:
# find min and max column wise
# print(r1.max)
# print(r1.max(axis=0))
# print(r1.max(axis=0))
print(r1.max(axis=1))
print(r1.min(axis=1))

[30 36 39]
[16 19 12]


In [108]:
# replace the last column with sum of all the columns
print(r1)
print()
m=r1.sum(axis=0)
r1[:,3]=m[0:3]
print(r1)


[[16 19 26 30]
 [36 19 27 34]
 [16 39 29 12]]

[[16 19 26 68]
 [36 19 27 77]
 [16 39 29 82]]


In [85]:
#create a matrix (3x4) R1 of random numbers between 10-40
r2=np.random.randint(10,40,size=(3,4))
print(r2)

[[14 27 35 10]
 [16 25 23 37]
 [14 24 36 11]]


In [114]:
#replace all even elements with nan in R1
print(r2)
print()
p=r2.astype('float16')
n=(p%2==0)
print(p[n])
print()
p[n]=np.nan
print(p)


[[14 27 35 10]
 [16 25 23 37]
 [14 24 36 11]]

[14. 10. 16. 14. 24. 36.]

[[nan 27. 35. nan]
 [nan 25. 23. 37.]
 [nan nan nan 11.]]


In [117]:
# count number of nan in R1
print(np.isnan(p).sum())

6


In [119]:
a1 = np.arange(1,10).reshape(3,3)
print()
a2 = np.arange(11,20).reshape(3,3)
print()
a3 = np.append(a1,a2)
print(a3)
print()
a3 = np.append(a1,a2, axis = 0)
print(a3)
print()
a3 = np.append(a1,a2, axis = 1)
print(a3)



[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
